# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y maven

COPY cloudwatch-exporter.service /home/ubuntu
COPY after-install.sh /home/ubuntu
COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV REF v0.15.5
ENV FPM_NAME "prometheus-cloudwatch-exporter"
ENV FPM_DESCRIPTION "A Prometheus exporter for Amazon CloudWatch"
ENV FPM_VERSION "0.15.5"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE " Apache-2.0"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://github.com/prometheus/cloudwatch_exporter"

ENTRYPOINT ["/home/ubuntu/build.sh"]
