---
global:
  smtp_smarthost: localhost:25
  smtp_from: alertmanager@localhost
templates:
- "/etc/alertmanager/*.tmpl"
route:
  group_by:
  - alertname
  - cluster
  - service
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email
  routes:
  - match_re:
      severity: ".*"
    receiver: email
receivers:
- name: email
  email_configs:
  - to: root@localhost
    from: prometheus@localhost
    smarthost: localhost:25
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
mute_time_intervals: []
