FROM docker.io/ubuntu:23.10

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

COPY build.sh /home/ubuntu/
COPY kafka-ic.tar.gz /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10

ENTRYPOINT ["/home/ubuntu/build.sh"]
