FROM docker.io/ubuntu:24.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

COPY build.sh /home/ubuntu/
COPY kafka-ic.tar.gz /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /output/ubuntu-24.04

ENTRYPOINT ["/home/ubuntu/build.sh"]
