# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

COPY build.sh /home/ubuntu/
COPY kafka-ic.tar.gz /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV BUILD_DIR /home/ubuntu/kafka-ic/kafka_2.11-1.1.1-SNAPSHOT
ENV REF 2.11
ENV FPM_NAME "kafka-ic"
ENV FPM_DESCRIPTION "Apache Kafka from Instaclustr"
ENV FPM_VERSION "2.11"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE "Apache-2.0"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://www.instaclustr.com"

ENTRYPOINT ["/home/ubuntu/build.sh"]
