# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV REF 0.8.2
ENV FPM_NAME "websocketpp"
ENV FPM_DESCRIPTION "WebSocket++ is a header only C++ library that implements RFC6455 The WebSocket Protocol"
ENV FPM_VERSION "0.8.2"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE "BSD-3-Clause"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://github.com/zaphoyd/websocketpp"

ENTRYPOINT ["/home/ubuntu/build.sh"]
