FROM docker.io/rockylinux:9

WORKDIR /root

RUN dnf -y install \
rpm-build \
ruby \
rubygems \
wget

RUN gem install fpm

COPY build.sh /root
COPY package_rocky.sh /root/package.sh
COPY blackbox_exporter.service /root
COPY blackbox-exporter.yaml /root
COPY after-install.sh /root
COPY after-upgrade.sh /root

ENV BASEDIR /root
ENV OUTPUT /output/rocky-9

ENTRYPOINT ["/root/build.sh"]
