FROM docker.io/rockylinux:9

WORKDIR /root

RUN dnf -y install \
  git \
  make \
  rpm-build \
  ruby \
  rubygems \
  wget

RUN gem install fpm

RUN wget --quiet https://go.dev/dl/go1.23.2.linux-amd64.tar.gz
RUN tar -zxf go1.23.2.linux-amd64.tar.gz
RUN mv go /usr/local

COPY build.sh /root
COPY package_rocky.sh /root/package.sh

ENV BASEDIR /root
ENV GOPATH /root
ENV OUTPUT /output/rocky-9

ENTRYPOINT ["/root/build.sh"]
