FROM --platform=$BUILDPLATFORM ubuntu:focal-20230126 as build

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install \
git \
make \
time \
wget

RUN wget --quiet https://go.dev/dl/go1.19.linux-amd64.tar.gz 
RUN tar -zxf go1.19.linux-amd64.tar.gz
RUN mv go /usr/local 

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV GOPATH /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-20.04

ENTRYPOINT ["/home/ubuntu/build.sh"]
