FROM docker.io/rockylinux:9

WORKDIR /root

RUN dnf -y install \
git \
golang \
make \
rpm-build \
ruby \
rubygems \
time \
wget

RUN gem install fpm

COPY build.sh /root
COPY package_rocky.sh /root/package.sh

ENV BASEDIR /root
ENV OUTPUT /output/rocky-9

ENTRYPOINT ["/root/build.sh"]
