FROM docker.io/ubuntu:24.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-24.04
ENV REF v0.6.0
ENV FPM_NAME "jwt-cpp"
ENV FPM_DESCRIPTION "A header only library for creating and validating JSON Web Tokens in C++11."
ENV FPM_VERSION "0.6.0"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE "MIT"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://github.com/Thalhammer/jwt-cpp"

ENTRYPOINT ["/home/ubuntu/build.sh"]
