FROM docker.io/ubuntu:22.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

ENV BASEDIR /home/ubuntu
ENV OUTPUT /output/ubuntu-22.04

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential

COPY build.sh /home/ubuntu/

ENTRYPOINT ["/home/ubuntu/build.sh"]
