# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV REF v3.0.1
ENV FPM_NAME "date-howardhinnant"
ENV FPM_DESCRIPTION "C++ header-only library for managing dates"
ENV FPM_VERSION "3.0.1"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE "MIT"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://github.com/HowardHinnant/date"

ENTRYPOINT ["/home/ubuntu/build.sh"]
