FROM docker.io/ubuntu:24.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-24.04
ENV FPM_NAME "date-howardhinnant"
ENV FPM_DESCRIPTION "C++ header-only library for managing dates"
ENV FPM_LICENSE "MIT"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://github.com/HowardHinnant/date"

ENTRYPOINT ["/home/ubuntu/build.sh"]
