FROM docker.io/ubuntu:24.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

ENV BASEDIR /home/ubuntu
ENV OUTPUT /output/ubuntu-24.04

RUN apt-get update
RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y golang

COPY after-install.sh /home/ubuntu
COPY after-upgrade.sh /home/ubuntu
COPY build.sh /home/ubuntu
COPY updates-exporter.service /home/ubuntu
COPY package_ubuntu.sh /home/ubuntu/package.sh

ENTRYPOINT ["/home/ubuntu/build.sh"]
