FROM docker.io/rockylinux:9

WORKDIR /root

RUN dnf -y install \
rpm-build \
ruby \
rubygems \
wget

RUN gem install fpm

COPY build.sh /root
COPY package_ubuntu.sh /root/package.sh
COPY node_exporter.service /root
COPY after-install.sh /root
COPY after-upgrade.sh /root

ENV BASEDIR /root
ENV OUTPUT /output/ubuntu-24.04

ENTRYPOINT ["/root/build.sh"]
