FROM docker.io/ubuntu:24.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    libkrb5-dev \
    libssl-dev \
    libuv1-dev \
    zlib1g-dev

COPY build.sh /home/ubuntu/
COPY after-install.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /output/ubuntu-24.04

#ENTRYPOINT ["/bin/sh"]
ENTRYPOINT ["/home/ubuntu/build.sh"]
