FROM docker.io/ubuntu:22.04

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential python3 cmake libpcre3-dev zlib1g-dev libgcrypt20-dev libicu-dev

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /output/ubuntu-22.04

ENTRYPOINT ["/home/ubuntu/build.sh"]
