# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential python3 cmake libpcre3-dev zlib1g-dev libgcrypt20-dev libicu-dev

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV REF v2.0.0.beta2

ENV FPM_LICENSE MIT
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://www.puppeteers.net"
ENV FPM_DESCRIPTION "High Performance C++ Web Framework"

ENTRYPOINT ["/home/ubuntu/build.sh"]
