# Right now this install Ubuntu 23.10, but will change to 24.04 when that gets
# released
FROM docker.io/ubuntu:rolling

WORKDIR /home/ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    binutils \
    git \
    ruby \
    rubygems

RUN gem install fpm

RUN apt-get install -y build-essential python3 cmake zlib1g-dev libssl-dev libcurlpp-dev

COPY build.sh /home/ubuntu/

ENV BASEDIR /home/ubuntu
ENV OUTPUT /home/ubuntu/output/ubuntu-23.10
ENV REF 1.11.217
ENV FPM_NAME "aws-sdk-cpp"
ENV FPM_DESCRIPTION "AWS SDK for C++"
ENV FPM_ITERATION "1"
ENV FPM_LICENSE "MIT"
ENV FPM_VENDOR "Puppeteers_Oy"
ENV FPM_MAINTAINER "info@puppeteers.net"
ENV FPM_URL "https://www.puppeteers.net"

ENTRYPOINT ["/home/ubuntu/build.sh"]
